version: '3.8'

services:
  desafio-target:
    build:
      context: .
      dockerfile: DesafioTarget/Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
